[package]
name = "blockbuster"
description = "Metaplex canonical program parsers, for indexing, analytics etc...."
version = "0.0.1"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/blockbuster"
license = "AGPL-3.0"
edition = "2021"
readme = "README.md"

[dependencies]
spl-compression = { git = "https://github.com/solana-labs/solana-program-library", features = ["no-entrypoint"] }
wrapper = { git = "https://github.com/solana-labs/solana-program-library", features = ["no-entrypoint"] }
mpl-bubblegum = { git = "https://github.com/metaplex-foundation/metaplex-program-library", rev="d78eb3bd021f59772e47097c9c7e654da59aec16", features = ["no-entrypoint"] }
spl-token = { version = "3.3.0", features = ["no-entrypoint"] }
spl-token-2022 = { version = "0.4.1", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "~1.0.5", features = ["no-entrypoint"] }
mpl-token-metadata = { version = "1.3.6", features = ["no-entrypoint"] }
plerkle_serialization = { path = "../digital-asset-validator-plugin/plerkle_serialization", version = ">=0.0.3" }
solana-sdk = "~1.10.38"
async-trait = "0.1.57"
lazy_static = "1.4.0"
flatbuffers = "2.1.2"
borsh = "0.9.3"
anchor-lang = "0.25.0"
thiserror = "1.0.32"
